# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 1
  tests: true
  issues:
    exclude-files:
      - \.pb\.go$
      - \.pb\.gw\.go$
    exclude-dirs:
      - bin
      - vendor
      - var
      - tmp
      - .cache
      - postgres/bin
      - postgres/migrations

output:
  formats: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    shadow: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - typecheck
    - unused

issues:
  exclude-use-default: false
  exclude-rules:
    - linters:
        - revive
      text: "don't use MixedCaps in package name"
  exclude:
    - G104 # _ instead of err checks
    - exported func .* returns unexported type .*, which can be annoying to use
    - should have a package comment
    - don't use an underscore in package name